defaults:
  - _self_

model:
   num_heads: 4
   qkv_feature_dim: 32
   max_seq_length: 2
   hidden_dims: [512, 512, 512]
   output_dims: [1024, 1024, 1024]
   condition_dims: [64, 64]
   time_dims: [512, 512]
   time_n_freqs: 1024
   flow_noise: 0.5
   learning_rate: 0.0001
   multi_steps: 10
   epsilon: 0.01
   tau_a: 1.0
   tau_b: 1.0

training:
  valid_freq: 1000
  num_iterations: 10000
  batch_size: 1024
  out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/combosciplex/out


dataset:
  adata_train_path: /lustre/groups/ml01/workspace/ot_perturbation/data/combosciplex/adata_train.h5ad
  adata_test_path: /lustre/groups/ml01/workspace/ot_perturbation/data/combosciplex/adata_test.h5ad
  adata_ood_path: /lustre/groups/ml01/workspace/ot_perturbation/data/combosciplex/adata_ood.h5ad
  obsm_key_data: X_pca
  obsm_key_cond_1: ecfp_drug_1
  obsm_key_cond_2: ecfp_drug_2


