# @package _global_

# Default configurations
defaults:
  - _self_
  - dataset: combosciplex_30
  - hydra: conf
  - model: default_combosciplex
  - launcher: slurm_icb
  - logger: default
  - training: training
