valid_freq: 400_000
num_iterations: 200_000 # 50_000
batch_size: 1024
test_n_conditions_on_log_iteration: 5
test_n_conditions_on_train_end: 0
ood_n_conditions_on_log_iteration: null # 
ood_n_conditions_on_train_end: null # null = all
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/norman_soren/cellflow/out # todo
save_path: /lustre/groups/ml01/workspace/ot_perturbation/data/norman_soren/cellflow/models # todo
save_model: False
save_predictions: False