condition_embedding_dim: 1024
time_encoder_dims: [1024, 1024, 1024]
time_encoder_dropout: 0.0
hidden_dims: [4096, 4096, 4096]
hidden_dropout: 0.0
decoder_dims: [4096, 4096, 4096]
decoder_dropout: 0.0
pooling: "mean"
layers_before_pool: 
  drugs:
    layer_type: mlp
    dims: [1024, 1024]
    dropout: 0.0
layers_after_pool:
  layer_type: mlp
  dims: [1024, 1024]
  dropout: 0.0
cond_output_dropout: 0.5
time_freqs: 1024
flow_noise: 1.0
learning_rate: 0.00005
multi_steps: 20
epsilon: 0.1
tau_a: 1.0
tau_b: 1.0
flow_type: "constant_noise"