hidden_dims: [512, 512, 512]
output_dims: [1024, 1024, 1024]
condition_dims: [64, 64]
time_dims: [512, 512]
time_n_freqs: 1024
flow_noise: 0.5
learning_rate: 0.0001
multi_steps: 10
epsilon: 0.01
tau_a: 1.0
tau_b: 1.0
