# @package _global_

# Default configurations
defaults:
  - _self_
  - dataset: combosciplex 
  - hparams_search: hparams_otfm
  - hydra: conf
  - model: default
  - launcher: slurm_icb
  - logger: default
  - training: training
  