# @package _global_

# Default configurations
defaults:
  - _self_
  - dataset: norman 
  - hparams_search: hparams_otfm
  - hydra: conf_norman
  - model: default
  - launcher: slurm_icb
  - logger: default_norman
  - training: training_norman
  