# @package _global_

# Default configurations
defaults:
  - _self_
  - dataset: sciplex_biolord_split
  - hparams_search: hparams_sciplex
  - hydra: conf
  - model: default
  - launcher: slurm_icb
  - logger: default
  - training: training
