# @package _global_

# Default configurations
defaults:
  - _self_
  - dataset: norman_0seen
  - hparams_search: hparams_norman
  - hydra: conf_norman
  - model: combosciplex
  - launcher: slurm_icb
  - logger: default_norman
  - training: training_norman
  