valid_freq: 125_000
num_iterations: 500_000
batch_size: 1024
train_fraction_for_validation: 0
test_n_conditions_on_log_iteration: 0
test_n_conditions_on_train_end: 0
ood_n_conditions_on_log_iteration: null
ood_n_conditions_on_train_end: null
n_cells_max_in_source_ood_at_log_iteration: 30000
n_cells_max_in_source_ood_at_train_end: 30000
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/models/otfm/pbmc
save_model: True
save_preds: True