valid_freq: 40_000
num_iterations: 200_000
batch_size: 1024
test_n_conditions_on_log_iteration: 2
test_n_conditions_on_train_end: 2
ood_n_conditions_on_log_iteration: null
ood_n_conditions_on_train_end: null
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/combosciplex/out
