valid_freq: 5000
num_iterations: 2000000
batch_size: 1024
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/norman/out
fast_metrics: True
n_test_samples: 3
n_train_samples: 0
n_ood_samples: 2
save_model: True
