valid_freq: 5000
num_iterations: 10000
batch_size: 1024
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/out
fast_metrics: True
n_test_samples: 5
n_train_samples: 0
n_ood_samples: -1