n_epochs_kl_warmup: 3
n_epochs_pretrain_ae: to_none
n_epochs_adv_warmup: to_none
n_epochs_mixup_warmup: to_none
mixup_alpha: 0.1
adv_steps: 5
n_hidden_adv: 64
n_layers_adv: 2
use_batch_norm_adv: true
use_layer_norm_adv: false
dropout_rate_adv: 0.2
reg_adv: 20.0
pen_adv: 20.0
lr: 0.0003
wd: 7.0e-07
adv_lr: 0.0003
adv_wd: 7.0e-07
adv_loss: cce
doser_lr: 0.0003
doser_wd: 7.0e-07
do_clip_grad: false
gradient_clip_value: 1.0
step_size_lr: 45