num_heads: 4
qkv_feature_dim: 32
max_seq_length: 2
hidden_dims: [512, 512, 512]
output_dims: [1024, 1024, 1024]
condition_dims: [4096, 4096, 4096]
condition_dims_forward: [512, 512]
condition_dims_post_attention: [512, 512]
time_dims: [512, 512, 512]
time_n_freqs: 1024
flow_noise: 1.0
learning_rate: 0.00005
multi_steps: 20
epsilon: 0.1
tau_a: 0.999
tau_b: 0.999
dropout_rate: 0.2
