# @package _global_

defaults:
  - override /hydra/sweeper/sampler: random
  - override /hydra/sweeper: optuna

optimized_metric: r_squared

hydra:
  sweeper:
    #_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    direction: minimize

    n_jobs: 1000

    n_trials: 1000

    sampler:
      _target_: optuna.samplers.RandomSampler

    # define hyperparameter search space
    params:
      dataset.sample_covariates: choice([cell_line])
      model.condition_embedding_dim: choice(1024)
      model.time_encoder_dims: choice([2048, 2048, 2048])
      model.time_encoder_dropout: choice(0.0)
      model.hidden_dims: choice([2048, 2048, 2048], [4096, 4096, 4096])
      model.decoder_dropout: choice(0.0, 0.1)
      model.decoder_dims: choice([1024, 1024, 1024], [2048, 2048, 2048])
      model.layers_before_pool.drugs.layer_type: choice(mlp)
      model.layers_before_pool.drugs.dims: choice([1024, 1024])
      model.layers_before_pool.drugs.dropout_rate: choice(0.0, 0.2, 0.5)
      model.layers_before_pool.dose.dims: choice([1024, 1024])
      model.layers_before_pool.dose.dropout_rate: choice(0.0)
      model.layers_before_pool.cell_line.layer_type: choice(mlp)
      model.layers_before_pool.cell_line.dims: choice([1024, 1024])
      model.layers_before_pool.cell_line.dropout_rate: choice(0.0)
      model.layers_after_pool.layer_type: choice(mlp)
      model.layers_after_pool.dims: choice([1024, 1024])
      model.layers_after_pool.dropout_rate: choice(0.0, 0.2, 0.5)
      model.cond_output_dropout: choice(0.5, 0.8)
      model.multi_steps: choice(20)
      model.tau_a: choice(0.99, 1.0)
      model.tau_b: choice(0.99, 1.0)
      model.epsilon: choice(0.01, 0.1)
      model.pooling: choice(mean)
      model.genot_source_layers.dims: choice([1024, 1024, 1924], [2048, 2048, 2048])
      model.genot_source_layers.dropout_rate: choice(0.0, 0.2, 0.5)

