iterations: 500000
batch_size: 1024
lr_init: 5.0e-05
lr_schedule: constant
lr_b1: 0.9
lr_b2: 0.999
opt_n_steps: 20
n_src_cells: 10000
n_src_cells_eval: 1000
cond_embed_dim: 128
pooling: mean
pool_sample_covariates: false
pool_num_heads: 0
pool_qkv_dim: 0
pool_dropout: 0.0
pool_act_fn: relu
pool_seed_dim: 0
pool_transformer_block: false
pool_layer_norm: false
cond_layers_before_pool: mlp
cond_n_layers_before_pool: 4
cond_hidden_dim_before_pool: 2048
cond_dropout_before_pool: 0.0
cond_layers_after_pool: mlp
cond_n_layers_after_pool: 0
cond_hidden_dim_after_pool: 256
cond_dropout_after_pool: 0.1
cond_output_dropout: 0.3
cond_num_heads: 0
cond_transformer: false
cond_layer_norm: false
cond_act_fn: relu
ot_num_layers_t: 5
ot_num_layers_x: 3
ot_num_layers_decoder: 2
ot_t_hidden_dim: 1024
ot_x_hidden_dim: 2048
ot_t_embed_dim: 1024
ot_x_embed_dim: 128
ot_joint_hidden_dim: 512
ot_act_fn: silu
ot_dropout_t: 0.1
ot_dropout_x: 0.2
ot_dropout_decoder: 0.1
ot_flow_type: constant_noise
ot_flow_noise: 0.0
ot_eps: 0.5
ot_tau_a: 0.99
ot_tau_b: 0.99
ot_n_frequencies: 1024
out_prefix: CHIR+SHH
minimal: false
