valid_freq: 200_000
num_iterations: 5_000_000
batch_size: 1024
test_n_conditions_on_log_iteration: 10
test_n_conditions_on_train_end: 10
ood_n_conditions_on_log_iteration: None
ood_n_conditions_on_train_end: None
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/sciplex/out
save_model: True
save_path: /lustre/groups/ml01/workspace/ot_perturbation/models/otfm/sciplex_biolord_split
