valid_freq: 1000
num_iterations: 10000
batch_size: 1024
out_dir: /lustre/groups/ml01/workspace/ot_perturbation/data/norman/out
fast_metrics: True
n_test_samples: 10
n_train_samples: 0
n_ood_samples: -1
save_model: False

