valid_freq: 10_000
num_iterations: 10_000
batch_size: 1024
test_n_conditions_on_log_iteration: 2
test_n_conditions_on_train_end: 2
ood_n_conditions_on_log_iteration: null
ood_n_conditions_on_train_end: null
out_dir: /lustre/groups/ml01/workspace/cell_flow_perturbation/zebrafish
save_model: True
save_path: /lustre/groups/ml01/workspace/cell_flow_perturbation/zebrafish
